name: Dev Publish crates (interfaces)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - run: echo "dev publish workflow sanity"
