name: Dev Publish crates (interfaces)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "sanity with checkout"